
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Chapter_Config : Luban.BeanBase
{
    public Chapter_Config(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        BackgroundImage = _buf.ReadString();
        ModeId = _buf.ReadInt();
        LevelGruop = _buf.ReadString();
    }

    public static Chapter_Config DeserializeChapter_Config(ByteBuf _buf)
    {
        return new Chapter_Config(_buf);
    }

    /// <summary>
    /// 章节id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 章节命
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 章节立绘背景图
    /// </summary>
    public readonly string BackgroundImage;
    /// <summary>
    /// 所属模式
    /// </summary>
    public readonly int ModeId;
    /// <summary>
    /// 关卡组合
    /// </summary>
    public readonly string LevelGruop;
   
    public const int __ID__ = -1656374348;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "backgroundImage:" + BackgroundImage + ","
        + "modeId:" + ModeId + ","
        + "levelGruop:" + LevelGruop + ","
        + "}";
    }
}

}
