
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Framework
{
public partial class ChapterCfg
{
    private readonly System.Collections.Generic.Dictionary<int, Chapter_Config> _dataMap;
    private readonly System.Collections.Generic.List<Chapter_Config> _dataList;
    
    public ChapterCfg(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Chapter_Config>();
        _dataList = new System.Collections.Generic.List<Chapter_Config>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Chapter_Config _v;
            _v = Chapter_Config.DeserializeChapter_Config(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Chapter_Config> DataMap => _dataMap;
    public System.Collections.Generic.List<Chapter_Config> DataList => _dataList;

    public Chapter_Config GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Chapter_Config Get(int key) => _dataMap[key];
    public Chapter_Config this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

