
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.resource
{ 
    public enum ResourceTypeEnum
    {
        /// <summary>
        /// 视频资源
        /// </summary>
        VIDEO = 1,
        /// <summary>
        /// 语音资源
        /// </summary>
        VOICE = 2,
        /// <summary>
        /// 特效资源
        /// </summary>
        EFFECT = 3,
        /// <summary>
        /// 音频资源
        /// </summary>
        MUSIC = 4,
    }

} 

