
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;
using Cysharp.Threading.Tasks;

namespace cfg
{
public partial class Tables
{
    public Framework.ChapterCfg ChapterCfg {get; private set; }

    /// public Tables(System.Func<string, ByteBuf> loader)
    public Tables()
    {
        ///        /// ChapterCfg = new Framework.ChapterCfg(loader("framework_chaptercfg"));
        ///        /// ResolveRef();
    }

    public async UniTask LoadAsync(System.Func<string, UniTask<ByteBuf>> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
		List<UniTask> list = new List<UniTask>();
		list.Add(UniTask.Create(async () =>
		{
			ChapterCfg = new Framework.ChapterCfg(await loader("framework_chaptercfg")); 
			tables.Add("Framework.ChapterCfg", ChapterCfg);
		}));

		await UniTask.WhenAll(list);

        ResolveRef();
    }
    
    private void ResolveRef()
    {
        ChapterCfg.ResolveRef(this);
    }
}

}
