
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.uiView
{ 
    public enum UIEventEnum
    {
        EVENT_SCENE_OBJECT_TRIGGER_SHOW_TIPS = 10001001,
        EVENT_PLAYER_JUMP = 10001002,
        EVENT_SCENE_LAOJUNYAN_TRIGGER_EYES = 10001003,
        EVENT_SCENE_LAOJUNYAN_TRIGGER_EARS = 10001004,
        EVENT_SCENE_LAOJUNYAN_TRIGGER_HEAD = 10001005,
    }

} 

