
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.uiView
{ 
    public enum ViewName
    {
        UILoading = 10000001,
        UILogin = 10000002,
    }

} 

